from .browser import BiDiBrowser
from .search_utils import find_firefox

import base64
import json
import logging
import os
from pathlib import Path
import shutil
import socket
import subprocess
import tempfile
import time
from urllib.parse import urlparse

from websocket import WebSocketTimeoutException, create_connection

logger = logging.getLogger(__name__)

BIDI_TIMEOUT = 30


class FirefoxBiDi(BiDiBrowser):
    """Firefox backend using the WebDriver BiDi protocol.

    Connects directly to Firefox's BiDi WebSocket endpoint
    (ws://127.0.0.1:<port>/session) without requiring geckodriver.

    Known limitations:
    - Transparent PNG backgrounds for standalone SVG files may render as
      opaque white instead of transparent. This is a BiDi protocol limitation.
    """

    def __init__(
        self,
        executable=None,
        flags=None,
        print_command=False,
        bidi_port=None,
        disable_logging=False,
    ):
        self.executable = executable
        if not flags:
            self.flags = []
        else:
            self.flags = [flags] if isinstance(flags, str) else list(flags)

        self.print_command = print_command
        self._bidi_port = bidi_port
        self._disable_logging = disable_logging

        self.proc = None
        self._ws = None
        self._session_id = None
        self._context_id = None
        self._profile_dir = None
        self._current_port = None
        self._message_id = 0

    @property
    def executable(self):
        return self._executable

    @executable.setter
    def executable(self, value):
        self._executable = find_firefox(value)

    @property
    def disable_logging(self):
        return self._disable_logging

    @disable_logging.setter
    def disable_logging(self, value):
        self._disable_logging = value

    @staticmethod
    def _normalize_input(input_value):
        if os.path.exists(input_value):
            return Path(input_value).resolve().as_uri()
        parsed = urlparse(input_value)
        if parsed.scheme:
            return input_value
        return input_value

    def _pick_port(self):
        if self._bidi_port is not None:
            return self._bidi_port
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            sock.bind(('127.0.0.1', 0))
            return int(sock.getsockname()[1])

    def _write_profile_prefs(self, profile_dir):
        Path(profile_dir).mkdir(parents=True, exist_ok=True)
        prefs = [
            '// File generated by html2image',
            'user_pref("devtools.chrome.enabled", true);',
            'user_pref("devtools.debugger.prompt-connection", false);',
            'user_pref("devtools.debugger.remote-enabled", true);',
            'user_pref("remote.active-protocols", 3);',
            'user_pref("fission.bfcacheInParent", false);',
            'user_pref("fission.webContentIsolationStrategy", 0);',
        ]
        Path(profile_dir, 'user.js').write_text(
            '\n'.join(prefs) + '\n', encoding='utf-8'
        )

    def _start_firefox(self):
        if self.proc is not None and self.proc.poll() is None:
            return

        self._profile_dir = tempfile.mkdtemp(prefix='html2image_firefox_bidi_')
        self._write_profile_prefs(self._profile_dir)
        self._current_port = self._pick_port()

        command = [
            str(self.executable),
            '--headless',
            '-no-remote',
            '--new-instance',
            '--profile', self._profile_dir,
            f'--remote-debugging-port={self._current_port}',
            *self.flags,
            'about:blank',
        ]

        if self.print_command:
            print(' '.join(command))

        if not self.disable_logging:
            logger.info(
                'Starting headless Firefox with --remote-debugging-port=%s.',
                self._current_port,
            )

        popen_kwargs = {}
        if self.disable_logging:
            popen_kwargs['stdout'] = subprocess.DEVNULL
            popen_kwargs['stderr'] = subprocess.DEVNULL

        creationflags = 0
        if os.name == 'nt':
            creationflags = getattr(subprocess, 'CREATE_NEW_PROCESS_GROUP', 0)
            creationflags |= getattr(subprocess, 'CREATE_NO_WINDOW', 0)

        self.proc = subprocess.Popen(
            command,
            creationflags=creationflags,
            **popen_kwargs,
        )

    def _bidi_send(self, method, **params):
        self._message_id += 1
        payload = {
            'id': self._message_id,
            'method': method,
            'params': params,
        }
        self._ws.send(json.dumps(payload))
        return self._message_id

    def _bidi_recv_until(self, predicate, timeout=BIDI_TIMEOUT):
        deadline = time.time() + timeout
        while time.time() < deadline:
            remaining = max(0.1, deadline - time.time())
            self._ws.settimeout(remaining)
            try:
                raw = self._ws.recv()
            except WebSocketTimeoutException as exc:
                raise TimeoutError(
                    f'Timed out after {timeout}s waiting for BiDi message'
                ) from exc
            message = json.loads(raw)
            matched = predicate(message)
            if matched:
                return matched
        raise TimeoutError(
            f'Timed out after {timeout}s waiting for matching BiDi message'
        )

    def _bidi_expect_ok(self, message_id, timeout=BIDI_TIMEOUT):
        message = self._bidi_recv_until(
            lambda m: m if m.get('id') == message_id else None,
            timeout=timeout,
        )
        if message.get('type') == 'error' or 'error' in message:
            raise RuntimeError(f'BiDi error for id={message_id}: {message}')
        return message

    def _connect_ws(self):
        self._start_firefox()

        ws_url = f'ws://127.0.0.1:{self._current_port}/session'

        # Try multiple connection strategies in order — Firefox version and
        # configuration affect which combination is accepted.
        strategies = [
            {'suppress_origin': True, 'subprotocols': ['webDriverBidi']},
            {'suppress_origin': True},
            {'subprotocols': ['webDriverBidi']},
            {},
        ]

        max_retries = 20
        retry_delay = 0.5
        last_error = None

        for attempt in range(max_retries):
            for strategy in strategies:
                try:
                    self._ws = create_connection(ws_url, timeout=10, **strategy)
                    logger.debug('Connected to Firefox BiDi WebSocket.')
                    self._new_session()
                    return
                except Exception as error:
                    last_error = error
                    if self._ws:
                        try:
                            self._ws.close()
                        except Exception:
                            pass
                        self._ws = None

            if attempt < max_retries - 1:
                logger.debug(
                    'BiDi connection attempt %d/%d failed. Retrying in %.1fs...',
                    attempt + 1, max_retries, retry_delay,
                )
                time.sleep(retry_delay)

        raise RuntimeError(
            f'Could not connect to Firefox BiDi on port {self._current_port} '
            f'after {max_retries} attempts.'
        ) from last_error

    def _new_session(self):
        status_id = self._bidi_send('session.status')
        self._bidi_expect_ok(status_id, timeout=10)

        session_response = self._bidi_expect_ok(
            self._bidi_send('session.new', capabilities={'alwaysMatch': {}}),
            timeout=30,
        )
        self._session_id = session_response['result']['sessionId']

        contexts = self._get_tree()
        if contexts:
            self._context_id = str(contexts[0]['context'])
        else:
            self._context_id = self._create_context()

    def _get_tree(self):
        response = self._bidi_expect_ok(self._bidi_send('browsingContext.getTree'))
        return list(response['result'].get('contexts', []))

    def _create_context(self):
        response = self._bidi_expect_ok(
            self._bidi_send('browsingContext.create', type='tab'),
            timeout=20,
        )
        return str(response['result']['context'])

    def _set_viewport(self, width, height):
        self._bidi_expect_ok(
            self._bidi_send(
                'browsingContext.setViewport',
                context=self._context_id,
                viewport={'width': width, 'height': height},
                devicePixelRatio=1,
            ),
            timeout=20,
        )

    def _navigate(self, url):
        self._bidi_expect_ok(
            self._bidi_send(
                'browsingContext.navigate',
                context=self._context_id,
                url=url,
                wait='complete',
            ),
            timeout=30,
        )

    def _capture(self, output_file_path, format_type):
        response = self._bidi_expect_ok(
            self._bidi_send(
                'browsingContext.captureScreenshot',
                context=self._context_id,
                origin='viewport',
                format={'type': format_type},
            ),
            timeout=30,
        )
        Path(output_file_path).write_bytes(base64.b64decode(response['result']['data']))

    def _shutdown_process_tree(self):
        if self.proc is None or self.proc.poll() is not None:
            return

        if os.name == 'nt':
            subprocess.run(
                ['taskkill', '/PID', str(self.proc.pid), '/T'],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                check=False,
            )
            try:
                self.proc.wait(timeout=5)
                return
            except subprocess.TimeoutExpired:
                pass
            subprocess.run(
                ['taskkill', '/PID', str(self.proc.pid), '/T', '/F'],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                check=False,
            )
            try:
                self.proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                pass
        else:
            self.proc.terminate()
            try:
                self.proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self.proc.kill()
                try:
                    self.proc.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    pass

    def screenshot(
        self,
        input,
        output_path,
        output_file='screenshot.png',
        size=(1920, 1080),
    ):
        """Take a screenshot using Firefox via WebDriver BiDi."""
        auto_started = self.proc is None or self.proc.poll() is not None
        if auto_started:
            self.__enter__()

        try:
            width, height = size if size else (1920, 1080)
            target_url = self._normalize_input(input)

            ext = os.path.splitext(output_file)[1].lower()
            format_type = 'image/jpeg' if ext in ('.jpg', '.jpeg') else 'image/png'

            self._set_viewport(width, height)
            self._navigate(target_url)
            self._capture(os.path.join(output_path, output_file), format_type)
        finally:
            if auto_started:
                self.__exit__()

    def __enter__(self):
        """Start Firefox and establish a BiDi session."""
        try:
            self._connect_ws()
            return self
        except Exception:
            self.__exit__()
            raise

    def __exit__(self, *exc):
        """Close the BiDi session and shut down Firefox."""
        if not self.disable_logging:
            logger.info(
                'Closing Firefox BiDi instance on port %s.',
                self._current_port,
            )

        if self._ws:
            try:
                end_id = self._bidi_send('session.end')
                self._bidi_expect_ok(end_id, timeout=10)
            except Exception:
                pass
            try:
                self._ws.close()
            except Exception:
                pass
            finally:
                self._ws = None
                self._session_id = None
                self._context_id = None

        self._shutdown_process_tree()
        self.proc = None

        if self._profile_dir:
            try:
                shutil.rmtree(self._profile_dir, ignore_errors=True)
            except Exception:
                pass
            finally:
                self._profile_dir = None
